tests/test_train.py

The `test_train` failed for me because `subprocess.Popen("python", ...)` does not ensure that the same virtual environment is used that was used to run the test. This PR fixes that issue.

Make sure that subprocess uses the same python interpreter

---

setup.py

This PR modifies package-level metadata. Following https://stackoverflow.com/questions/2852283/python-naming-a-module-that-has-a-two-word-name , I decided to go with "bsmetadata" (short for BigScience Metadata) as a package name, but I'm open to any suggestions for alternative names.

Modify values for package setup

---

bsmetadata/input_pipeline.py
bsmetadata/metadata_utils.py
tests/test_metadata_utils.py

This PR adds a parameter `metadata_probability` to the `DataConfig`, which controls the probability of adding metadata to an input example.
Right now, whether to add metadata is decided once for each input (as opposed to making individual decisions for each chunk) - we might want to change this later.

Randomly include metadata with a given probability

---

bsmetadata/metadata_utils.py
tests/test_get_dataloaders.py

Fix #22 
In this PR, I propose to remove the `global_metadata_sep` when not adding global metadata but only local ones.
I changed the test accordingly :slightly_smiling_face:

Remove global metadata separator when there is only local metadata

---

.github/workflows/test.yml
poetry.lock
pyproject.toml
requirements.txt
setup.py

I will use code review comments to describe what I've done for the PR.
~~Three~~Two side notes:
1. Python 3.7.11 is for Colab;~~Although python>=3.8.10 also supports Apple Silicon and BigSur, 3.9 syntax is nicer for Black formatting;~~
~~2. GitHub Action doesn't have a roadmap for Apple M1 VM, therefore `test.yml` isn't really for the case;~~
1. Poetry is optional for managing venv and dependencies, but syncing with requirements(-dev).txt must be done manually for the time being.

build: set Python and dependency versions with an optional Poetry env

---

bsmetadata/experiments/with_metadata.py
bsmetadata/experiments/without_metadata.py
bsmetadata/input_pipeline.py
bsmetadata/metadata_processors.py
bsmetadata/metadata_utils.py
bsmetadata/train.py
tests/test_get_dataloaders.py
tests/test_metadata_utils.py
tests/test_train.py

In this PR I propose several changes that affect the dataset part of our script.
First, datasets uses caches. Caches are notably generated by `map` functions and their name depends on the hash of the function's parameters. `args` unfortunately had a non-deterministic hash, I propose to solve that.
Next, I propose two new arguments: `extension` and `map_batch_size`. The first is to be able to bring more generality than the extension guessed automatically by the code. The other argument is to adjust the batch size used by the map function of `datasets`. With a small batch size it is possible to reduce the risk of OOM (even if I still have some on big datasets) but for some operations (the `without_metatdata` script) the batch size still matters if the dataset examples are small (in this …

Improve `datasets` capabilities

---

bsmetadata/metadata_utils.py

When adding only global metadata (without global metadata at the beginning see #23), there was an offset of 1 on the metadata mask. This PR proposes to resolve this offset.

Fix metadata mask for local only metadata

---

bsmetadata/preprocessing_utils.py

This pull request is part of a proposal for how we can preprocess the C4 and Wikipedia datasets to get them into the format described [here](https://github.com/bigscience-workshop/metadata#metadata-format). Basically, everyone working on a specific kind of metadata would have to implement their own, metadata-specific `MetadataPreprocessor` which defines a single `preprocess` function that takes as input a set of examples and outputs the same set of examples, but with the particular metadata added.
The `preprocess` function is supposed to be used to perform [batch mapping](https://huggingface.co/docs/datasets/about_map_batch.html) with the `map` function from Huggingface's datasets. That is, on a high level, we'd do something like:
```python
ds = ... # load the original dataset, do some …
```

Add preprocessing utils interface.

---

.gitmodules
bsmetadata/preprocessing_utils.py
tests/test_parse_date.py

A few notes for discussion:
* I submodule my modified version of `dateutil` inside this repo, so there is no risk of messing up the dependency with `pip install -e`
* There are some mixed use of `import dateutil` and relative import in `dateutil`, but that doesn't seem to be an issue, so I left it that way.
I tried to use a simple regex to parse, and find the difference with this version, and here are some of the dates the regex did not parse.
```python
r"(20[0-2][0-9]|19\d\d)[/\-](0?[1-9]|10|11|12)[/\-](0?[1-9]|[12]\d|3[01])"
```
```text
/news/2018/sep/24/community-calendar-sept-25-2018/
/entertainment/lehigh-valley-music/mc-ent-elvis-costello-review-sands-bethlehem-event-center-20181103-story.html
/news/2017/jan/01/births-announcements-part-ii-january-1-2016/ …
```

Add timestamp processor

---

bsmetadata/train.py

The current way of passing config to wandb would cause parameteres in nested configs like 'data_config' to be displayed all in one field on wandb.
By passing a nested dictionary instead of dataclass, wandb will put each leaf in separate field.
Before:
```json
"data_config": {
"desc": null,
"value": "DataConfig(metadata_config=MetadataConfig(metadata_list=[], local_metadata_special_tokens=None, metadata_sep=' | ', metadata_key_value_sep=': ' 
...
"
},
```
After:
```json
"data_config": {
"desc": null,
"value": {
"metadata_config": {
"metadata_sep": " | ",
"metadata_list": [],
"metadata_prefix_sep": " |||",
"metadata_key_value_sep": ": ",
},
...
```

Fix wandb config

---

setup.py

When I tried to install the package on JZ, I got an error (a timeout error if I remember correctly).
I'm not absolutely sure, but I think that the `git+git://github.com/cccntu/dateutil@2.8.5` dependency requires an ssh setup to perform the installation. As I don't have an ssh setup with my github account on jz, I suggest to change the dependency declaration for `bs_dateuil` as this package is hosted on a public repository to use an https connection. With this modification, the installation is successful on JZ. :slightly_smiling_face:

fix: change `bs_dateuil` github dependency in `setup.py`

---

experiments/jz/toy_experiments/README.md
experiments/jz/toy_experiments/dumpdb/dumpdb.py
experiments/jz/toy_experiments/dumpdb/dumpdb.slurm

I open this PR to show you the script I ran for the moment on JZ to check that we could use `wikipedia2vec` which relies on the use of a `lmbd` database whose data are gathered in a `.db` file. I used for this test a toy database kindly shared by @shanyas10.
Good news @shanyas10 : everything works fine! :confetti_ball: 
@Timo, do we want to merge this kind of scripts on master?

feat: add `dumpdb` toy script

---

bsmetadata/preprocessing_tools/website_desc_utils.py

As discussed offline with @shanyas10 , we need to have a try/except in the `fetch_wikipedia_description_for_title` method if the title is not in the database. 
On the other hand, we can be more precise on the type of error to be catched in order to have other types of errors raised (like for example when we forgot to install the punkt model necessary to`nltk.sent_tokenize`)

fix: reduce try/except scope into `fetch_wikipedia_description_for_title`

---

bsmetadata/preprocessing_tools/html_parser/objects.py

This PR propose just to convert the specific Comment type of `lxml` that is not recognized by pyarrow (the underlying format used by `datasets`)

Handle the comment specific type not recognized by pyarrow

---

bsmetadata/preprocessing_tools/wikipedia_desc_utils.py

Fix #101 
During my last test, I notice that the list of paragraphs can be empty (can you confirm that this could happen @manandey and @shanyas10 ?)

Handle IndexError in `WikipediaDescUtils` for wikitext

---

bsmetadata/preprocessing_utils.py

To be able to run the code on a partition without internet, I need to download the flair model and to use it afterwards I need to fill in the path to the file in the `load_flair_ner` method.
cc @timoschick for visibility

add `path_or_url_flair_ner_model` in order to execute the entity extraction on a partition without internet

---

bsmetadata/preprocessing_utils.py
tests/test_entity_preprocessor.py

Before this PR, the extraction of named entities required an "id" column, I propose with this PR to generate on the fly the ids needed for batching in the REL library. This feature allows to avoid having to design an ids column upstream.
cc @timoschick , @norakassner

feat: change how the entity extraction process use ids

---

bsmetadata/preprocessing_utils.py
tests/mocks/mock_dump_db.py
tests/test_preprocessing_utils.py

Here is the beginning of the PR discussed in the meeting. This RP includes:
- the possibility to choose in which column the metadata are extracted
- create the column if it does not exist
- a new `UrlProcessor` to extract the url in the same format as the other metadata
- tests that extract in cascade several types of metadata (in the case 1) where they are extracted in different columns and 2) in the same column): can you all see if the extraction on this toy dataset suits you? :pray: 
Ready for review:
- Timestamp @cccntu 
- Website Desc @shanyas10 
- Entities @manandey (please note that I've addded some mocks to test your entities extraction in our github workflows)
- Datasource & Generation Length @chkla (I've pinged you on some part of the code because I've included some changes I've …

feat: add a feature to choose where to extract metadata

---

experiments/jz/joint_training_toy/joint_training_toy1/03_create_dataset.slurm

There was a small error that crept into the training scripts, if you put `SBATCH --gres=gpu:1` and `SBATCH --account=six@cpu` together, it creates a SLURM allocation error. This PR proposes to remove the instruction that blocks the job.

bug: fix the toy joint training slurm scripts

---

bsmetadata/experiments/with_metadata.py
bsmetadata/train.py
experiments/jz/joint_training_toy/joint_training_toy2-fp16/01_load_tokenizer_and_model.slurm
experiments/jz/joint_training_toy/joint_training_toy2-fp16/02_load_dataset.slurm
experiments/jz/joint_training_toy/joint_training_toy2-fp16/03_create_dataset.slurm
experiments/jz/joint_training_toy/joint_training_toy2-fp16/04_do_training.slurm
experiments/jz/joint_training_toy/joint_training_toy2-fp16/README.md
experiments/jz/joint_training_toy/joint_training_toy2-fp16/multi_steps.bash
experiments/jz/joint_training_toy/joint_training_toy3-fp16-multigpu/01_load_tokenizer_and_model.slurm
experiments/jz/joint_training_toy/joint_training_toy3-fp16-multigpu/02_load_dataset.slurm
experiments/jz/joint_training_toy/joint_training_toy3-fp16-multigpu/03_create_dataset.slurm
experiments/jz/joint_training_toy/joint_training_toy3-fp16-multigpu/04_do_training.slurm
experiments/jz/joint_training_toy/joint_training_toy3-fp16-multigpu/README.md
experiments/jz/joint_training_toy/joint_training_toy3-fp16-multigpu/local_test.sh
experiments/jz/joint_training_toy/joint_training_toy3-fp16-multigpu/multi_steps.bash

* Changed an argument in load_dataset so it tries to read private datasets.
* Added gradient_step logging, so we can see time v.s. gradient step on wandb
* Adds 2 sub-experiments
1.  + fp16
2.  + fp16, 2 GPU
* note: I only have 1 GPU, so I couldn't test this one, but I included a `local_test.sh` that can be used to test.
* The toy dataset used is now privated. To run the experiments, you'd need to configure the huggingface access tokens with `huggingface-cli  login`.

Add fp16, multi-GPU training script (toy dataset)

---

bsmetadata/experiments/with_metadata.py
bsmetadata/metadata_processors.py
bsmetadata/metadata_utils.py

According to discussion with @timoschick . 
Added a function to sample metadata as follows:
1. uniformly decide how many types of metadata should be included.
2. randomly choose metadata types to include.
WIP: need to add test and add code to actually call this function.

Add code to sampling multiple metadata

---

bsmetadata/evaluation.py
bsmetadata/plot_losses.py

Example:
```
Meta
[('html', 9.2), (' ||', 5.62), ('|', 5.3), ('<', 3.03), ('div', 2.33), (' id', 8.1), (':', 5.23), ('content', 10.28), (' body', 8.08), ('Content', 6.66), (' class', 0.74), (':', 5.57), ('m', 3.76), ('w', 0.56), ('-', 4.58), ('body', 6.57), (' m', 0.03), ('w', 0.12), ('-', 2.72), ('body', 1.14), ('-', 3.66), ('content', 4.03), ('><', 2.86), ('h', 0.95), ('1', 0.58), ('>', 6.97), ('Media', 4.35), ('Wiki', 6.57), (' 1', 0.17), ('.', 7.35), ('30', 2.5), ('.', 1.34), ('0', 11.42), (' installation', 0.89), ('</', 0.0), ('h', 0.0), ('1', 0.85), ('>', 2.75), ('\n', 10.94), ('<', 1.59), ('div', 0.5), (' class', 0.54), (':', 8.27), ('config', 1.08), ('-', 3.54), ('page', 0.9), ('-', 4.53), ('wrapper', 2.67), ('><', 1.79), ('div', 0.18), (' class', 0.26), (':', 2.22), ('config', …
```

Add loss plotting
